theme: jekyll-theme-slate
title: SummarIA
description: This project aims to create a tool for people in the legal sector aimed to highlight key sentences of a document for a quicker ingestion of its content.
